CREATE TABLE Trafic_Crashes (
	CRASH_DATE DATE,
	POSTED_SPEED_LIMIT INT, 
	TRAFFIC_CONTROL_DEVICE VARCHAR(255), 
	DEVICE_CONDITION VARCHAR(255),
	WEATHER_CONDITION VARCHAR(255),
	LIGHTING_CONDITION VARCHAR(255),
	CRASH_REASON VARCHAR(255),
	TRAFFICWAY_TYPE VARCHAR(255),
	ROAD_ALIGNMENT VARCHAR(255),
	ROADWAY_SURFACE_COND VARCHAR(255),
	ROAD_DEFECT VARCHAR(255),
	CRASH_TYPE VARCHAR(255),
	DAMAGE VARCHAR(255),
	CONTRIBUTORY_CAUSE VARCHAR(255),
	WORK_ZONE_TYPE VARCHAR(255),
	NUM_UNITS FLOAT,
	INJURY_TYPE VARCHAR(255),
	INJURIES_TOTAL FLOAT,
	CRASH_HOUR INT,
	CRASH_DAY_OF_WEEK INT,
	CRASH_MONTH INT, 
	LATITUDE FLOAT,
	LONGITUDE FLOAT,
	CRASH_YEAR INT

);



DROP TABLE Trafic_Crashes